---
# Composite action to use as step in workflows
#
# - version matrix is defined in a workflow's job strategy

name: 'Setup Python'
description: 'Install Python, pip dependencies and ansible'

runs:
  using: 'composite'

  steps:

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/requirements.txt'

    - name: Install pip dependencies
      shell: bash
      run: pip install -r requirements.txt

    - name: Install ansible versions
      shell: bash
      run: pip install ansible-core==${{ matrix.ansible-core-version }}
