---
# Variables specific on MS Azure platform, Virtual Machines
#
# TODO: make sure to first respect 'ha_cluster' native variables

sap_ha_pacemaker_cluster_fence_agent_packages:
  - fence-agents-azure-arm

__sap_ha_pacemaker_cluster_platform_extra_packages:
  - socat

__sap_ha_pacemaker_cluster_repos:
  - id: "rhel-{{ ansible_distribution_major_version }}-for-{{ ansible_architecture }}-highavailability-e4s-rhui-rpms"
    name: High Availability
  - id: "rhui-microsoft-azure-rhel8-sap-ha"
    name: Microsoft Azure RPMs for Red Hat Enterprise Linux 8 (rhel8-sap-ha)

# Predefine
__sap_ha_pacemaker_cluster_msazure_hosts: []

# Fencing via MS Azure Managed Service Identity (MSI) per cluster node
sap_ha_pacemaker_cluster_stonith_default:
  id: "res_fence_azure_arm"
  agent: "stonith:fence_azure_arm"
  options:
    msi: true
    subscriptionId: "{{ sap_ha_pacemaker_cluster_msazure_subscription_id }}"
    resourceGroup: "{{ sap_ha_pacemaker_cluster_msazure_resource_group }}"

# Platform specific VIP handling
sap_ha_pacemaker_cluster_vip_method: azure_lb

# The VIP layer consists of 2 components - the VIP and the health check resource
sap_ha_pacemaker_cluster_vip_group_prefix: group_

#sap_ha_pacemaker_cluster_vip_hana_primary_resource_name: "vip_{{ sap_ha_pacemaker_cluster_hana_sid }}_{{ sap_ha_pacemaker_cluster_hana_instance_nr }}_primary"
#sap_ha_pacemaker_cluster_vip_hana_secondary_resource_name: "vip_{{ sap_ha_pacemaker_cluster_hana_sid }}_{{ sap_ha_pacemaker_cluster_hana_instance_nr }}_readonly"
#sap_ha_pacemaker_cluster_vip_nwas_abap_ascs_resource_name: "vip_{{ sap_ha_pacemaker_cluster_nwas_abap_sid }}_{{ sap_ha_pacemaker_cluster_nwas_abap_ascs_instance_nr }}_ascs"
#sap_ha_pacemaker_cluster_vip_nwas_abap_ers_resource_name: "vip_{{ sap_ha_pacemaker_cluster_nwas_abap_sid }}_{{ sap_ha_pacemaker_cluster_nwas_abap_ers_instance_nr }}_ers"
#sap_ha_pacemaker_cluster_vip_nwas_abap_pas_resource_name: "vip_{{ sap_ha_pacemaker_cluster_nwas_abap_sid }}_{{ sap_ha_pacemaker_cluster_nwas_abap_pas_instance_nr }}_pas"
#sap_ha_pacemaker_cluster_vip_nwas_abap_aas_resource_name: "vip_{{ sap_ha_pacemaker_cluster_nwas_abap_sid }}_{{ sap_ha_pacemaker_cluster_nwas_abap_aas_instance_nr }}_aas"

#sap_ha_pacemaker_cluster_healthcheck_hana_primary_resource_name: "hc_{{ sap_ha_pacemaker_cluster_vip_hana_primary_resource_name }}"
#sap_ha_pacemaker_cluster_healthcheck_hana_secondary_resource_name: "hc_{{ sap_ha_pacemaker_cluster_vip_hana_secondary_resource_name }}"
#sap_ha_pacemaker_cluster_healthcheck_nwas_abap_ascs_resource_name: "hc_{{ sap_ha_pacemaker_cluster_vip_nwas_abap_ascs_resource_name }}"
#sap_ha_pacemaker_cluster_healthcheck_nwas_abap_ers_resource_name: "hc_{{ sap_ha_pacemaker_cluster_vip_nwas_abap_ascs_resource_name }}"
#sap_ha_pacemaker_cluster_healthcheck_nwas_abap_pas_resource_name: "hc_{{ sap_ha_pacemaker_cluster_vip_nwas_abap_pas_resource_name }}"
#sap_ha_pacemaker_cluster_healthcheck_nwas_abap_aas_resource_name: "hc_{{ sap_ha_pacemaker_cluster_vip_nwas_abap_aas_resource_name }}"

__sap_ha_pacemaker_cluster_available_vip_agents:

  # IPaddr2 requires a Virtual IP within a common Network (i.e. 1 VLAN / 1 VPC / 1 VNet), one or more Subnets may be used
  # With this design restriction, IPaddr2 is only to be used for High Availability within a single location (i.e. 1 Availability Zone / Datacenter / Location within 1 Region)
  ipaddr:
    agent: "ocf:heartbeat:IPaddr2"

  # Use nc/socat to listen for and respond to health check probe monitoring requests from Azure Load Balancer,
  # if failure to respond then the Load Balancer will perform failover activities
  azure_lb:
    agent: "ocf:heartbeat:azure-lb"
    with: ipaddr
