---
# Included in: tasks/main.yml

- name: "SAP HA Prepare Pacemaker - Add order constraint: Primary VIP starts after DB is promoted"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_constraints_order: "{{ __sap_ha_pacemaker_cluster_constraints_order + [__constraint_order_vip] }}"
  vars:
    __constraint_order_vip:
      resource_first:
        id: "{{ sap_ha_pacemaker_cluster_hana_resource_clone_name }}"
        action: promote
      resource_then:
        id: "{{ __res_or_grp }}"
        action: start

    # Check if there is
    # - a group for the hana_primary VIP/HC resources
    # - otherwise check if the VIP resource for hana_primary is defined
    # - otherwise check for a HC resource for hana_primary
    # and use the found resource in the constraint.
    __res_or_grp: |-
      {% if sap_ha_pacemaker_cluster_vip_group_prefix | length > 0 and
        __sap_ha_pacemaker_cluster_resource_groups | map(attribute='id')
        | select('match', sap_ha_pacemaker_cluster_vip_group_prefix + sap_ha_pacemaker_cluster_vip_hana_primary_resource_name) -%}
        {{ sap_ha_pacemaker_cluster_vip_group_prefix }}{{ sap_ha_pacemaker_cluster_vip_hana_primary_resource_name }}
      {%- elif __sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id')
        | select('match', sap_ha_pacemaker_cluster_vip_hana_primary_resource_name) -%}
        {{ sap_ha_pacemaker_cluster_vip_hana_primary_resource_name }}
      {%- elif __sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id')
        | select('match', sap_ha_pacemaker_cluster_healthcheck_hana_primary_resource_name) -%}
        {{ sap_ha_pacemaker_cluster_healthcheck_hana_primary_resource_name }}
      {%- else -%}
        none_found
      {%- endif -%}

  when:
    - __constraint_order_vip.resource_then not in (__sap_ha_pacemaker_cluster_constraints_order | map(attribute='resource_then'))
    - __res_or_grp != 'none_found'  # fallback skip if there was neither a group nor any VIP/HC resources found

- name: "SAP HA Prepare Pacemaker - Add order constraint: Read-only VIP starts after DB on the secondary"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_constraints_order: "{{ __sap_ha_pacemaker_cluster_constraints_order + [__constraint_order_vip] }}"
  vars:
    __constraint_order_vip:
      resource_first:
        id: "{{ sap_ha_pacemaker_cluster_hana_resource_clone_name }}"
        action: start
      resource_then:
        id: "{{ __res_or_grp }}"
        action: start

    # Check if there is
    # - a group for the hana_secondary VIP/HC resources
    # - otherwise check if the VIP resource for hana_secondary is defined
    # - otherwise check for a HC resource for hana_secondary
    # and use the found resource in the constraint.
    __res_or_grp: |-
      {% if sap_ha_pacemaker_cluster_vip_group_prefix | length > 0 and
        __sap_ha_pacemaker_cluster_resource_groups | map(attribute='id')
        | select('match', sap_ha_pacemaker_cluster_vip_group_prefix + sap_ha_pacemaker_cluster_vip_hana_secondary_resource_name) -%}
        {{ sap_ha_pacemaker_cluster_vip_group_prefix }}{{ sap_ha_pacemaker_cluster_vip_hana_secondary_resource_name }}
      {%- elif __sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id')
        | select('match', sap_ha_pacemaker_cluster_vip_hana_secondary_resource_name) -%}
        {{ sap_ha_pacemaker_cluster_vip_hana_secondary_resource_name }}
      {%- elif __sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id')
        | select('match', sap_ha_pacemaker_cluster_healthcheck_hana_secondary_resource_name) -%}
        {{ sap_ha_pacemaker_cluster_healthcheck_hana_secondary_resource_name }}
      {%- else -%}
        none_found
      {%- endif -%}

  when:
    - __constraint_order_vip.resource_then not in (__sap_ha_pacemaker_cluster_constraints_order | map(attribute='resource_then'))
    - __res_or_grp != 'none_found'  # fallback skip if there was neither a group nor any VIP/HC resources found


# The primary VIP only runs where HANA is promoted
- name: "SAP HA Prepare Pacemaker - Add colocation constraint: Primary VIP runs where HANA is promoted"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_constraints_colocation: "{{ __sap_ha_pacemaker_cluster_constraints_colocation + [__constraint_colo_vip] }}"
  vars:
    __constraint_colo_vip:
      resource_leader:
        id: "{{ sap_ha_pacemaker_cluster_hana_resource_clone_name }}"
        role: promoted
      resource_follower:
        id: "{{ __res_or_grp }}"
      options:
        - name: score
          value: "{{ __colo_score }}"

    ## Group or single resource?
    # Check if there is
    # - a group for the hana_primary VIP/HC resources
    # - otherwise check if the VIP resource for hana_primary is defined
    # - otherwise check for a HC resource for hana_primary
    # and use the found resource in the constraint.
    __res_or_grp: |-
      {% if sap_ha_pacemaker_cluster_vip_group_prefix | length > 0 and
        __sap_ha_pacemaker_cluster_resource_groups | map(attribute='id')
        | select('match', sap_ha_pacemaker_cluster_vip_group_prefix + sap_ha_pacemaker_cluster_vip_hana_primary_resource_name) -%}
        {{ sap_ha_pacemaker_cluster_vip_group_prefix }}{{ sap_ha_pacemaker_cluster_vip_hana_primary_resource_name }}
      {%- elif __sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id')
        | select('match', sap_ha_pacemaker_cluster_vip_hana_primary_resource_name) -%}
        {{ sap_ha_pacemaker_cluster_vip_hana_primary_resource_name }}
      {%- elif __sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id')
        | select('match', sap_ha_pacemaker_cluster_healthcheck_hana_primary_resource_name) -%}
        {{ sap_ha_pacemaker_cluster_healthcheck_hana_primary_resource_name }}
      {%- else -%}
        none_found
      {%- endif -%}

    ## When in a group, increase the default base score by adding 1000 per resource in the group.
    __colo_score: >-
      {% if __sap_ha_pacemaker_cluster_resource_groups | length > 0 -%}
        {% for group in __sap_ha_pacemaker_cluster_resource_groups -%}
          {% if group.id == (sap_ha_pacemaker_cluster_vip_group_prefix
            + sap_ha_pacemaker_cluster_vip_hana_primary_resource_name) -%}
            {{ (group.resource_ids | length * 1000) + sap_ha_pacemaker_cluster_constraint_colo_base_score }}
          {%- endif %}
        {%- endfor %}
      {%- else -%}
        {{ sap_ha_pacemaker_cluster_constraint_colo_base_score }}
      {%- endif %}

  when:
    - __constraint_colo_vip.resource_follower not in (__sap_ha_pacemaker_cluster_constraints_colocation | map(attribute='resource_follower'))
    - __res_or_grp != 'none_found'  # fallback skip if there was neither a group nor any VIP/HC resources found


# The secondary VIP only runs where HANA is UNpromoted
- name: "SAP HA Prepare Pacemaker - Add colocation constraint: Read-only VIP runs where HANA is not promoted"
  ansible.builtin.set_fact:
    __sap_ha_pacemaker_cluster_constraints_colocation: "{{ __sap_ha_pacemaker_cluster_constraints_colocation + [__constraint_colo_vip] }}"
  vars:
    __constraint_colo_vip:
      resource_leader:
        id: "{{ sap_ha_pacemaker_cluster_hana_resource_clone_name }}"
        role: unpromoted
      resource_follower:
        id: "{{ __res_or_grp }}"
      options:
        - name: score
          value: "{{ __colo_score }}"

    # Check if there is
    # - a group for the hana_secondary VIP/HC resources
    # - otherwise check if the VIP resource for hana_secondary is defined
    # - otherwise check for a HC resource for hana_secondary
    # and use the found resource in the constraint.
    __res_or_grp: |-
      {% if sap_ha_pacemaker_cluster_vip_group_prefix | length > 0 and
        __sap_ha_pacemaker_cluster_resource_groups | map(attribute='id')
        | select('match', sap_ha_pacemaker_cluster_vip_group_prefix + sap_ha_pacemaker_cluster_vip_hana_secondary_resource_name) -%}
        {{ sap_ha_pacemaker_cluster_vip_group_prefix }}{{ sap_ha_pacemaker_cluster_vip_hana_secondary_resource_name }}
      {%- elif __sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id')
        | select('match', sap_ha_pacemaker_cluster_vip_hana_secondary_resource_name) -%}
        {{ sap_ha_pacemaker_cluster_vip_hana_secondary_resource_name }}
      {%- elif __sap_ha_pacemaker_cluster_resource_primitives | map(attribute='id')
        | select('match', sap_ha_pacemaker_cluster_healthcheck_hana_secondary_resource_name) -%}
        {{ sap_ha_pacemaker_cluster_healthcheck_hana_secondary_resource_name }}
      {%- else -%}
        none_found
      {%- endif -%}

    ## When in a group, increase the default base score by adding 1000 per resource in the group.
    __colo_score: >-
      {% if __sap_ha_pacemaker_cluster_resource_groups | length > 0 -%}
        {% for group in __sap_ha_pacemaker_cluster_resource_groups -%}
          {% if group.id == (sap_ha_pacemaker_cluster_vip_group_prefix
            + sap_ha_pacemaker_cluster_vip_hana_secondary_resource_name) -%}
            {{ (group.resource_ids | length * 1000) + sap_ha_pacemaker_cluster_constraint_colo_base_score }}
          {%- endif %}
        {%- endfor %}
      {%- else -%}
        {{ sap_ha_pacemaker_cluster_constraint_colo_base_score }}
      {%- endif %}

  when:
    - __constraint_colo_vip.resource_follower not in (__sap_ha_pacemaker_cluster_constraints_colocation | map(attribute='resource_follower'))
    - sap_ha_pacemaker_cluster_vip_hana_secondary_ip_address is defined
    - sap_ha_pacemaker_cluster_vip_hana_secondary_ip_address != ''
    - __res_or_grp != 'none_found'  # fallback skip if there was neither a group nor any VIP/HC resources found
