---
# This REUSABLE workflow

name: Dummy Testing

on: 
  push:
#  workflow_call:
#  workflow_dispatch:
#    input:
#      test:
#        description: 'role'
#        type: choice
#        options:
#          - eins
#          - zwei


jobs:
  setup:
    name: test changed files
    runs-on: ubuntu-latest

    outputs:
      chfiles: ${{ steps.changed-files.outputs.test }}

    steps:
      # Check out code to get files and workflow requirements
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Revision
        id: changed-files
        run: |
          git branch -a
          BASE=$(diff -u <(git rev-list --first-parent HEAD) <(git rev-list --first-parent refs/remotes/origin/dev) | sed -ne 's/^ //p' | head -1)
          git diff --name-only HEAD ${BASE} >> $GITHUB_OUTPUT

  list:
    name: List changed files
    runs-on: ubuntu-latest

    steps:
        
      - shell: bash
        run: |
          echo ${{ needs.setup.outputs.chfiles }}
