---
# This REUSABLE workflow

name: Dummy Testing

on: 
  push:
#  workflow_call:
#  workflow_dispatch:
#    input:
#      test:
#        description: 'role'
#        type: choice
#        options:
#          - eins
#          - zwei

jobs:
  setup:
    name: test something
    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#
#      # Do not cancel all jobs if one of the matrix jobs fails
#      fail-fast: false

    steps:
      # Check out code to get files and workflow requirements
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Review 
        uses: actions/dependency-review-action@v3
        with:
          base-ref: origin/dev
          head-ref: origin/main
