---
# This REUSABLE workflow

name: Dummy Testing

on: 
  push:
#  workflow_call:
#  workflow_dispatch:
#    input:
#      test:
#        description: 'role'
#        type: choice
#        options:
#          - eins
#          - zwei


jobs:
  setup:
    name: test changed files
    runs-on: ubuntu-latest

    steps:
      # Check out code to get files and workflow requirements
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Revision
        id: changed-files
        run: |
          PARENT='origin/dev'
          BASE=$(diff -u <(git rev-list --first-parent HEAD) <(git rev-list --first-parent ${PARENT}) | sed -ne 's/^ //p' | head -1)
          git diff --name-only HEAD ${BASE}

      - name: List files
        run: |
          git diff --name-only HEAD ${BASE}
